#!/bin/bash
# -*- coding: utf-8 -*-
#
#  rm_openarena
#  
#  Copyright 2018 Thomas Castleman <draugeros@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
if [[ "$EUID" == "0" ]]; then
    echo "Please do not run {rm_openarena} as root. This causes file system issues."
    exit 2
fi
read -p "Are you sure you wish to uninstall OpenArena? [y/N]: " answer
if [ "$answer" == "y" ] || [ "$answer" == "Y" ]; then
  x="$HOME"
  pkexec rm -r $x/.openarena /bin/rm_openarena /usr/share/applications/OpenArena.desktop
  echo -e "\nOpenArena uninstalled.\n"
else
  echo -e "\nExiting . . . \n"
fi
  
